import sql from "./db"

let migrated = false
export async function migrate() {

    if (migrated) return
    migrated = true

    console.log("checking/creating a new notes table")

    await sql`
        create table if not exists notes (
            id bigint generated by default as identity primary key,
            created_at timestamp with time zone not null default now(),
            modified_at timestamp with time zone null default now(),
            title text null,
            markdown text null,
            public_uuid UUID default gen_random_uuid() unique,
            public_url boolean default false,
            public_pane boolean default false
        )
    `

    //toodo remove this stuff below after publish but add in future updates
    await sql`
        alter table notes
        add column if not exists modified_at timestamp with time zone null default now()
    `
    await sql`
        alter table notes
        add column if not exists public_url boolean default false
    `
    await sql`
        alter table notes
        add column if not exists public_pane boolean default false
    `
    await sql`
        alter table notes
        add column if not exists public_uuid UUID default gen_random_uuid() unique
    `
}

export async function getNotes() {
    await migrate()

    const notes = await sql`
        select * from notes order by created_at desc
    `

    return notes
}

export async function getNoteByID(id) {
    await migrate()

    const [note] = await sql`
        select *
        from 
            notes
        where
            id = ${id}
    `

    return note || null
}

export async function getNoteByUUID(uuid) {
    await migrate()

    const [note] = await sql`
        select *
        from 
            notes
        where
            public_uuid = ${uuid}
    `

    return note || null
}

export async function addNote(markdown, public_url, public_pane) {
    await migrate()

    const [note] = await sql`
        insert into notes 
            (markdown, public_url, public_pane)
        values
            (${markdown}, ${public_url}, ${public_pane})
        returning *
    `

    return note
}

export async function modifyNote(id, markdown, public_url, public_pane) {
    await migrate()


    //replace any missing data with old data
    const oldData = await getNoteByID(id)

    if (markdown === undefined) {
        markdown = oldData.markdown
    }

    if (public_url === undefined) {
        public_url = oldData.public_url
    }
    
    if (public_pane === undefined) {
        public_pane = oldData.public_pane
    }

    const [note] = await sql`
        update notes
        set 
            modified_at = now(),
            markdown = ${markdown},
            public_url = ${public_url},
            public_pane = ${public_pane}
        where id = ${id}
        returning *
    `

    return note
}

export async function removeNote(id) {
    await migrate()

    const [note] = await sql`
        delete from notes
        where
            id = ${id}
        returning *
    `

    return note
}