import sql from "./db"

let migrated = false
export async function migrate() {

    if (migrated) return
    migrated = true

    console.log("creating a new notes table")

    await sql`
        create table if not exists notes (
            id bigint generated by default as identity primary key,
            created_at timestamp with time zone not null default now(),
            modified_at timestamp with time zone null default now(),
            title text null,
            markdown text null,
            public_uuid UUID default gen_random_uuid() unique,
            public_url boolean default false,
            public_pane boolean default false
        )
    `

    //toodo remove this stuff below after publish but add in future updates
    await sql`
        alter table notes
        add column if not exists modified_at timestamp with time zone null default now()
    `
    await sql`
        alter table notes
        add column if not exists public_url boolean default false
    `
    await sql`
        alter table notes
        add column if not exists public_pane boolean default false
    `
    await sql`
        alter table notes
        add column if not exists public_uuid UUID default gen_random_uuid() unique
    `
}

export async function getNotes() {
    const notes = await sql`
        select * from notes order by created_at desc
    `

    return notes
}

export async function getNote(id) {
    const [note] = await sql`
        select *
        from 
            notes
        where
            id = ${id}
    `

    return note || null
}

export async function addNote(markdown) {
    const [note] = await sql`
        insert into notes 
            (markdown)
        values
            (${markdown})
        returning *
    `

    return note
}

export async function removeNote(id) {
    const [note] = await sql`
        delete from notes
        where
            id = ${id}
        returning *
    `

    return note
}